// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/17/2026, 3:15:47 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/m.shohan/Downloads/e-commerce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/plugins/**/*.{js,ts,mjs}","C:/Users/m.shohan/Downloads/e-commerce/composables/**/*.{js,ts,mjs}","C:/Users/m.shohan/Downloads/e-commerce/utils/**/*.{js,ts,mjs}","C:/Users/m.shohan/Downloads/e-commerce/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/m.shohan/Downloads/e-commerce/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;